export const CLOSE_FORM = 'CLOSE_FORM';
export const OPEN_FORM = 'OPEN_FORM';
export const OPEN_FORM_WITH_DATA = 'OPEN_FORM_WITH_DATA';

export const DATA_WAS_NOT_POSTED = 'DATA_WAS_NOT_POSTED';
export const DATA_WAS_POSTED = 'DATA_WAS_POSTED';
export const DATA_WAS_UPDATED = 'DATA_WAS_UPDATED';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG';
export const OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG';
